name: badminstoreapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
      - assets/files/
      - assets/images/
      - assets/images/categories/
      - assets/images/intro/
      - assets/images/products/
      - assets/images/slider/
